.\" Copyright (c) 2020-2026, Matthew Wilson and Synesis Information Systems
.\"
.TH RSTRIP 1 "August 2026" "rstrip 0.1.2" "User Commands"
.SH NAME
rstrip \- remove trailing whitespace from input lines
.SH SYNOPSIS
.B rstrip
[\fIOPTIONS\fR]
[\fIINPUT\fR [\fIOUTPUT\fR]]
.SH DESCRIPTION
.B rstrip
removes trailing whitespace from each input line. Input and output default to
standard input and standard output when omitted or specified as
.BR \- .
.SH OPTIONS
.B rstrip
accepts the following options:
.TP
.B \-\-help
Display help and exit.
.TP
.B \-\-version
Display version information and exit.
.SH SEE ALSO
.BR chomp (1),
.BR lstrip (1)
.SH REPORTING BUGS
Report defects and feature requests at
https://github.com/sistools/rstrip.
.SH AUTHOR
Matthew Wilson and Synesis Information Systems
.br
Copyright (c) 2020\-2026, Matthew Wilson and Synesis Information Systems
